language: csharp
mono: none
dotnet: 2.0.0
dist: trusty

branches:
  only:
    - master
    - develop

addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main'
      key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
    - dotnet-hostfxr-1.0.1
    - dotnet-sharedframework-microsoft.netcore.app-1.0.5
    - docker-ce

sudo: required

services:
  - docker

script:
    - cd webapi/HelloCoreApi/HelloCoreApi/
    - dotnet restore && dotnet build
    - export REPO=sanjaywadhwani/hellocore
    - docker build -t $REPO:$COMMIT .
    
after_success:
  - docker login -e $DOCKER_EMAIL -p $DOCKER_PASS
  - export REPO=sanjaywadhwani/hellocore
  - docker tag $REPO:$COMMIT $REPO:$TRAVIS_BRANCH
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO:$COMMIT